### ISSUE TITLE
Tracking issue: Documentation

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket2#203]
This is a tracking issue for improving the documentation and examples of the crate.

- [ ] Expand the README.
  Explain what is this, what is this for, etc.
  List the different members of the worksplace (libs and bins).
- [ ] Crate level description.
  Expand the crate doc in `src/lib.rs`, to provide an introduction and links to resources (similar to the README).
  Include some doctests showing how this works.
  Document the features.
- [ ] Add `examples/` with some small usecases. (Serialising / deserialising, validating, ...)
  Depending on how much we can encode in the doctests, these may not be needed.

- [ ] `tket2` submodule docs.
  Review and expand documentation as needed. Add doctests showing the usage.
- [ ] `taso-optimiser` README
- [ ] `compile-rewriter` README
