### ISSUE TITLE
Tracking issue: Python bindings UX

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket2#204]
This is a tracking issue for improvements to the python API.

## Documentation & repo structure

- [x] CQCL/tket2#207
- [x] CQCL/tket2#169
- [x] CQCL/tket2#229

## Issues

- [x] CQCL/tket2#208
  E.g. `from pyrs.pyrs import optimiser`.
- [x] CQCL/tket2#209
  It requires importing `optimiser` first.

### DAG queries

- [ ] CQCL/tket2#226
- [ ] CQCL/tket2#225
- [x] CQCL/tket2#227
- [x] CQCL/tket2#178

### Matching and rewriting
- [ ] Expose rewrite primitives (SimpleRewrite, Inline*)
- [ ] Rewrite combinators / rewrite strategies.
- [x] ~TASO~Badger as a `CustomPass`. CQCL/tket2#185 

### Construction

- [x] CQCL/hugr#946 
- [x] CQCL/tket2#303 
- [ ] Control flow builder
