### ISSUE TITLE
tracking issue: Lower guppy-generated `Circuit`s into `pytket`

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket2#377]
Given a `tket2.Circuit` generated from a guppy definition (see #303), rewrite into something that can be translated into a `tket_json_rs::SerialCircuit`.

The following tasks are the bare minimum to support a restricted subset of guppy programs:

- [x] #380
    - This may be a Hugr-side pass
- [x] #407
- [x] #379
    - Translate the measurements and classically controlled operations.
- [x] #389 
- [x] #418 

Extended tket1 support:

- [ ] Translate classically controlled operations into tket2 (and back)
- [ ] https://github.com/CQCL/tket2/issues/44
- [ ] Translate tk1 logical expressions
- [ ] #428
- [ ] Support n-qubit controlled operations

Extended hugr support:

- [ ] https://github.com/CQCL/hugr/issues/818
- [ ] Flatten TailLoops
- [ ] Flatten Conditionals
- [ ] Inline function calls

**Comment by aborgna-q** [comment]
Closing this as completed since the core tasks are done. I opened two new tracking issues for the other categories
