### ISSUE TITLE
tracking issue: Extended tket1 decoding support

### ISSUE THREAD

**Issue by aborgna-q** [CQCL/tket2#503]
Continuation from #377 

- [ ] Translate classically controlled operations into tket2 (and back)
- [ ] https://github.com/CQCL/tket2/issues/44
- [ ] Translate tk1 logical expressions
- [ ] #428
- [ ] Support n-qubit controlled operations
