### ISSUE TITLE
Tracking issue: run tket1 passes on subgraphs

### ISSUE THREAD

**Issue by ss2165** [CQCL/tket2#634]
The goal is to identify suitable regions of HUGRs on which tket1 passes can be used for optimisation, extract, run, and replace.

Tasks:

- [ ] #633 
- [ ] Extract qubit subgraphs to pytket (including symbol creation for angles)
- [ ] Set up calling of pytket
- [ ] Replace identified subgraphs using new pytket circuits

**Comment by acl-cqc** [comment]
There are also #633 and #636 that might be want to be worked into this
